<?php

namespace ManagerITBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DesktopRamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesktopRamRepository extends EntityRepository
{
}
