<?php

namespace ManagerITBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends EntityRepository
{
    public function findAllDisconnect()
    {
        $em = $this->getEntityManager();
        
        $licenses = $em->getRepository('ManagerITBundle:License')->findAll();
        //$diff = array_merge(array_diff($tablica1,$tablica2));
        return $licenses;
        
    }
}
