<?php

namespace ManagerITBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsRepository extends EntityRepository
{
}
