
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN:       ROLE_BOSS
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN }
        - { path: ^/application/./, role: ROLE_ADMIN }
        - { path: ^/computer/laptop/./, role: ROLE_ADMIN }
        - { path: ^/computer/desktop/\d*/, role: ROLE_ADMIN }
        - { path: ^/computer/desktop/\D, role: ROLE_ADMIN }
        - { path: ^/employee/./, role: ROLE_ADMIN }
        - { path: ^/license/./, role: ROLE_ADMIN }
        - { path: ^/phone/./, role: ROLE_ADMIN }
        - { path: ^/printer/./, role: ROLE_ADMIN }
        - { path: ^/sim/./, role: ROLE_ADMIN }
        - { path: ^/tablet/./, role: ROLE_ADMIN }
        - { path: ^/computerformfactor, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }