# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

parameters:
    pictures_directory: '%kernel.root_dir%/../web/pictures'
    pdf_directory: '%kernel.root_dir%/../web/pdf'

services:
    # ...
    app.picture_uploader:
        class: ManagerITBundle\FileUploader
        arguments: ['%pictures_directory%']

    app.pdf_uploader:
        class: ManagerITBundle\FileUploader
        arguments: ['%pdf_directory%']

    app.twig_extension:
        class: ManagerITBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }